### ISSUE TITLE
ライセンスお願いします。

### ISSUE THREAD

**Issue by soukouki** [Lacty/Noncopyable#1]
ライセンスが出ていないので使えません。
お願いします。

**Comment by Lacty** [comment]
使用したいけど、ライセンスが表記されてないので
ライセンス表記をしてほしい
という認識でよろしいでしょうか

READMEにライセンスフリーと書いておきました
（僕はライセンス関係よく理解してないです・・・

**Comment by soukouki** [comment]
すみませんreadmeを見忘れました。

**Comment by soukouki** [comment]
ありがとうございました。
